import type { Metadata } from "next";
import { poppinsFont, interFont, cinzelDecorativeFont, latoFont } from "../config/fonts";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import ThemeProviderWrapper from "@/providers/themeProviderWrapper";
import "../styles/globals.css";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppinsFont.variable} ${interFont.variable} ${cinzelDecorativeFont.variable} ${latoFont.variable}`}
    >
      <body>
        <AppRouterCacheProvider>
          <ThemeProviderWrapper> {children}</ThemeProviderWrapper>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
