import type { Metadata } from "next";
import { poppinsFont, interFont, cinzelDecorativeFont } from "../config/fonts";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import ThemeProviderWrapper from "@/providers/themeProviderWrapper";
import { ToasterProvider } from "@/providers/ToasterProvider";
import "../styles/globals.css";
import NavBar from "@/components/layout/navbar/NavBar";
import Footer from "@/components/layout/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppinsFont.variable} ${interFont.variable} ${cinzelDecorativeFont.variable}`}
    >
      <body>
        <AppRouterCacheProvider>
          <ThemeProviderWrapper>
            {/* ✅ نضيف الـ ToasterProvider هنا */}
            <ToasterProvider>
              <NavBar />
              {children}
              <Footer />
            </ToasterProvider>
          </ThemeProviderWrapper>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
