import type { Metadata } from "next";
import {poppinsFont,interFont,cinzelDecorativeFont} from "../config/fonts"
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { theme } from "../config/theme";
import { ThemeProvider } from "@mui/material";
import { CssBaseline } from "@mui/material";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppinsFont.variable} ${interFont.variable} ${cinzelDecorativeFont.variable}`}>
      <body >
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}> {children}</ThemeProvider>
          <CssBaseline />
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
